name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_MODAL_URL: ${{secrets.NEXT_PUBLIC_MODAL_URL}}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm' 
      - run: pnpm install
      - run: pnpm run build

  backend:
    runs-on: ubuntu-latest
    needs: frontend
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    env:
      MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
      MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: |
          python -m pip install --upgrade pip
          pip install modal
      - run: modal deploy backend.app